apiVersion: apps/v1
kind: Deployment
metadata:
  name: profiler-demo-deployment
spec:
  replicas: 2  # Number of pod replicas
  selector:
    matchLabels:
      app: profiler-demo
  template:
    metadata:
      labels:
        app: profiler-demo
    spec:
      containers:
      - name: profiler-demo-container
        image: keelandmm/profiler-demo-project:latest  # Use the Docker Hub image
        ports:
        - containerPort: 9090  # Spring Boot app port
---
apiVersion: v1
kind: Service
metadata:
  name: profiler-demo-service
spec:
  selector:
    app: profiler-demo
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 9090  # Container port
  type: NodePort  # Or LoadBalancer depending on your environment
